data:
  dataset_path: 'data/GOLD_XYZ_OSC.0001_1024.hdf5'
  mod_name: 'QPSK'
  snr: 18
  test_split: 0.1

train:
  batch_size: 64
  learning_rate: 0.0002
  adam_b1: 0.8
  adam_b2: 0.99
  lr_decay: 0.999
  epochs: 200
  checkpoint_interval: 10
  log_interval: 10

model:
  input_channels: 2          # 输入：理想 I/Q
  output_channels: 2         # 输出：真实 I/Q
  # 上采样配置：2*2*2 = 8倍。输入128 -> 输出1024
  upsample_rates: [2, 2, 2]
  upsample_kernel_sizes: [4, 4, 4]
  upsample_initial_channel: 256
  # MRF残差块配置
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  # 判别器配置
  mpd_periods: [2, 4, 8, 16, 32] # 适配 SPS=8

loss:
  lambda_iq: 45.0      # 波形重建损失权重
  lambda_adv: 1.0      # 对抗损失权重
  lambda_fm: 2.0       # 特征匹配损失权重